### ISSUE TITLE
string 목록 업데이트 요청

### ISSUE THREAD

**Issue by aaei924** [skinmaker1345/nr-local-kor#8]
1.14버전이 되면서 스트링 목록이 업데이트된 것 같습니다. 반영을 요청드립니다.

**Comment by skinmaker1345** [comment]
확인 후 업데이트 완료하였습니다. 감사합니다.

**Comment by aaei924** [comment]
최근 추가된 string이 있는 것 같습니다. 업데이트 요청드립니다.
